### ISSUE TITLE
Arlo company now separate from Netgear, change with download servers

### ISSUE THREAD

**Issue by kcmd** [janick/ArloDownload#4]
Arlo is now a separate company from Netgear. As such, the video download servers are changing from being hosted under netgear.com to being hosted under arlo.com. Effective 1 October 2019 the netgear.com hosting will terminate. Can this code be adjusted to work under the new domain? Specific details as to the most new URLs are to be determined, as will impact variables loginUrl, deviceUrl, metadataUrl and libraryUrl.

**Comment by janick** [comment]
Just pushed an updated version with the updated URLs

**Comment by kcmd** [comment]
Thank you!
